### ISSUE TITLE
Increase open file limit in api and cable startup scripts

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-omnibus#11]
Ingestions can run into open file limits.

See https://github.com/castiron/pancho-puppet/commit/454cd4e2f5aa9208ff946432bc02a1c15149db21

**Comment by scryptmouse** [comment]
For consistency's sake, we may want to also apply this to sidekiq's startup script, in case workers ever have to do processing on ingestion (and so Sidekiq's processes have the same environmental limitations as the two pumas)
