### ISSUE TITLE
Expose a fallback web root for files such as robots.txt

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold-omnibus#49]
Our nginx config has /opt/manifold/embedded/src/client/dist/manifold/www set as the root. There are valid cases for adding files to the webroot, such as a custom robots.txt file, so we may want to expand our nginx config to fallback to a directory that the admin controls.

**Comment by tingletech** [comment]
I think this can be closed?

From slack

“The way to do this would be with the `nginx['custom_nginx_config']` setting in `/etc/manifold/manifold.rb`. You can include arbitrary nginx configuration in there that will be added to `/var/opt/manifold/nginx/conf/manifold-http.conf` when you run `manifold-ctl reconfigure`

“You could experiment with adding the redirect config directly to `manifold-http.conf` , keeping in mind you’d want to `manifold-ctl restart nginx` after changing that conf file for the change to be picked up. Once you found the nginx config you liked, move it to that `nginx['custom_nginx_config']` setting and run reconfigure ”

Above was regarding redirecting to the canonical hostname -- but seems like this would work for setting a robots.txt as well?

**Comment by zdavis** [comment]
Yes, I expect it would!
